defaults:
  - data: redwine
  - pred_model: mlp_small
  - projector: I
  - _self_

device: [0] # relevant devices are given by list (-1 is cpu) # this might not work on cluster
device_torch: "cuda:0"
seed: 2
dtype: "float64"

plot:
  evaluation:
    # if null (None) all methods from the dataframe are plotted
    methods: null
    legend: # display information in legend
      reduction_type: True
      psi: False

hydra:
  job:
    chdir: False  