name: Sigma
store: False # should the operator to reduce the dimension be stored?
# batches and chunk_size determine the storage cost to compute the projector P
batch_size: 100 # batch size to compoute projector
n_batches: 10 # number of iterations to compute the Jacobian.
# The Jacobian is computed for `batch_size * n_batches` samples
chunk_size: null # number of vjp to compute the Jacobian for computing P
# If None, the maximum chunk size is used. 
# If 1, then compute the jacobian row-by-row with a for-loop
name_postfix: "" # String to be appended on file name

# arguments to compute the matrix to construct Fisher information I = V.T @ V
v:
    n_batches: null
    batch_size: 100

# arguments used for fitting the posterior using the laplace library
fit:
    batch_size: 100

# `s` is the dimension of the subspace.
s:
    n: 10 # number of values linearly
    # interpolated between `s_min` and `s_max` (both values included)
    min: 10 
    max: null # null takes maximum size of the projection matrix. It is the
    # minimum of number_of_parameters and number_of_data_points * n_class

# computation of the predictive covariance Sigma_P = J P (P^T Psi^-1 P)^-1 P^T J
sigma:
    # Note even though method.p and method.psi are both used to compute the 
    # posterior psi. They are used in different context. The first is used to 
    # find the projector P and the second to construct the posterior Psi in 
    # Sigma_P
    method:
    # method.p defines the computation of the posterior to construct the 
    # projector P. diag, magnitude, swag, kron are approximations computed 
    # by the Laplace library. ggn uses the full generalized Gauss-Newton matrix
    # to compute P and loadfile loads a posterior from a file
    # method.psi defines the computation of Psi in Sigma_P. 
        # possible values: lowrank-diag, lowrank-kron, lowrank-ggnit, 
        #                  lowrank-full, lowrank-loadfile 
        #                  lowrankoptimal-diag, lowrankoptimal-kron, 
        #                  lowrankoptimal-ggnit, lowrankoptimal-full, 
        #                  lowrankoptimal-loadfile 
        #                  subset-magnitude, subset-swag, subset-diag 
        p: lowrank-kron 
        psi: ggnit # possible values: ggnit, kron, full, loadfile
    prior_precision: 1.0

# if the posterior is loaded
posterior_hessian: 
    load:
        type: I
        name: "I1279.pt"



layers_to_ignore: [BatchNorm2d]